import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class BpListService {
  constructor() {}

  getBpList() {
    return [
      {
        zpCode: 109,
        bpList: [
          { code: 1400, value: 'Shamsabad' },
          { code: 1395, value: 'Jaitpur Kalan' },
          { code: 1396, value: 'Khandauli' },
          { code: 1386, value: 'Achhnera' },
          { code: 1392, value: 'Fatehabad' },
          { code: 1397, value: 'Kheragarh' },
          { code: 1399, value: 'Saiyan' },
          { code: 1394, value: 'Jagner' },
          { code: 1389, value: 'Barauli Ahir' },
          { code: 1398, value: 'Pinahat' },
        ],
      },
      {
        zpCode: 110,
        bpList: [
          { code: 1401, value: 'Akrabad' },
          { code: 1403, value: 'Bijauli' },
          { code: 1411, value: 'Lodha' },
          { code: 1407, value: 'Gonda' },
          { code: 1412, value: 'Tappal' },
          { code: 1409, value: 'Jawan' },
          { code: 1410, value: 'Khair' },
          { code: 1404, value: 'Chandaus' },
          { code: 1402, value: 'Atrauli' },
          { code: 1406, value: 'Gangiri' },
        ],
      },
      {
        zpCode: 111,
        bpList: [
          { code: 1416, value: 'Dhanupur' },
          { code: 1415, value: 'Chaka' },
          { code: 1425, value: 'Mauaima' },
          { code: 1423, value: 'Koraon' },
          { code: 296948, value: 'Sringverpur Dham' },
          { code: 1431, value: 'Soraon' },
          { code: 1432, value: 'Uruwan' },
          { code: 296951, value: 'Bhagwatpur' },
          { code: 1413, value: 'Bahadurpur' },
          { code: 1429, value: 'Saidabad' },
        ],
      },
      {
        zpCode: 112,
        bpList: [
          { code: 1441, value: 'Tanda' },
          { code: 1437, value: 'Jahangir Ganj' },
          { code: 1433, value: 'Akbarpur' },
          { code: 1434, value: 'Baskhari' },
          { code: 1436, value: 'Bhiyawan' },
          { code: 1439, value: 'Katehari' },
          { code: 1438, value: 'Jalal Pur' },
          { code: 1435, value: 'Bhiti' },
          { code: 1440, value: 'Ram Nagar' },
        ],
      },
      {
        zpCode: 113,
        bpList: [
          { code: 1443, value: 'Ajitmal' },
          { code: 1446, value: 'Bidhuna' },
          { code: 1442, value: 'Achchalda' },
          { code: 1447, value: 'Erwa Katra' },
          { code: 1444, value: 'Auraiya' },
          { code: 1445, value: 'Bhagyanagar' },
          { code: 1448, value: 'Sahar' },
        ],
      },
      {
        zpCode: 114,
        bpList: [
          { code: 1460, value: 'Mirzapur' },
          { code: 1455, value: 'Koilsa' },
          { code: 1463, value: 'Palhani' },
          { code: 1456, value: 'Lalganj' },
          { code: 1461, value: 'Mohammadpur' },
          { code: 1469, value: 'Tarwa' },
          { code: 1457, value: 'Mahrajganj' },
          { code: 1453, value: 'Haraiya' },
          { code: 1464, value: 'Pawai' },
          { code: 1465, value: 'Phulpur' },
        ],
      },
      {
        zpCode: 115,
        bpList: [
          { code: 1476, value: 'Pilana' },
          { code: 1474, value: 'Chhaprauli' },
          { code: 1475, value: 'Khekra' },
          { code: 1472, value: 'Baraut' },
          { code: 1471, value: 'Baghpat' },
          { code: 1473, value: 'Binauli' },
        ],
      },
      {
        zpCode: 116,
        bpList: [
          { code: 1478, value: 'Chitaura' },
          { code: 1477, value: 'Balaha' },
          { code: 1487, value: 'Risia' },
          { code: 1485, value: 'Phakharpur' },
          { code: 1486, value: 'Prayagpur' },
          { code: 1489, value: 'Tajwapur' },
          { code: 1482, value: 'Mahasi' },
          { code: 1481, value: 'Kaisarganj' },
          { code: 1480, value: 'Jarwal' },
          { code: 1484, value: 'Nawabganj' },
        ],
      },
      {
        zpCode: 117,
        bpList: [
          { code: 1492, value: 'Bansdih' },
          { code: 1497, value: 'Garwar' },
          { code: 1501, value: 'Nagra' },
          { code: 1495, value: 'Chilkahar' },
          { code: 1499, value: 'Maniar' },
          { code: 1498, value: 'Hanumanganj' },
          { code: 1506, value: 'Siar' },
          { code: 1502, value: 'Navanagar' },
          { code: 1496, value: 'Dubhar' },
          { code: 1503, value: 'Pandah' },
        ],
      },
      {
        zpCode: 118,
        bpList: [
          { code: 1512, value: 'Pachpedwa' },
          { code: 1510, value: 'Gaisri' },
          { code: 1514, value: 'Shriduttganj' },
          { code: 1513, value: 'Rehera Bazaar' },
          { code: 1515, value: 'Tulsipur' },
          { code: 1511, value: 'Harriya Satgharwa' },
          { code: 1516, value: 'Utraula' },
          { code: 1508, value: 'Balrampur' },
          { code: 1509, value: 'Gaindas Bujurg' },
        ],
      },
      {
        zpCode: 179,
        bpList: [
          { code: 2206, value: 'Araria' },
          { code: 2207, value: 'Bhargama' },
          { code: 2208, value: 'Forbesganj' },
          { code: 2209, value: 'Jokihat' },
          { code: 2210, value: 'Kursakanta' },
          { code: 2211, value: 'Narpatganj' },
          { code: 2212, value: 'Palasi' },
          { code: 2213, value: 'Raniganj' },
          { code: 2214, value: 'Sikty' },
        ],
      },
      {
        zpCode: 180,
        bpList: [
          { code: 2215, value: 'Aurangabad' },
          { code: 2216, value: 'Barun' },
          { code: 2217, value: 'Daudnagar' },
          { code: 2218, value: 'Deo' },
          { code: 2219, value: 'Goh' },
          { code: 2220, value: 'Haspura' },
          { code: 2221, value: 'Kutumba' },
          { code: 2222, value: 'Madanpur' },
          { code: 2223, value: 'Nabinagar' },
          { code: 2224, value: 'Obra' },
          { code: 2225, value: 'Rafiganj' },
        ],
      },
      {
        zpCode: 181,
        bpList: [
          { code: 2226, value: 'Amarpur' },
          { code: 2227, value: 'Banka' },
          { code: 2228, value: 'Barahat' },
          { code: 2229, value: 'Bausi' },
          { code: 2230, value: 'Belhar' },
          { code: 2231, value: 'Chandan' },
          { code: 2232, value: 'Dhuraiya' },
          { code: 2233, value: 'Fullidumar' },
          { code: 2234, value: 'Katoria' },
          { code: 2235, value: 'Rajaun' },
          { code: 2236, value: 'Shambhuganj' },
        ],
      },
      {
        zpCode: 182,
        bpList: [
          { code: 2237, value: 'Bachhwara' },
          { code: 2238, value: 'Bakhri' },
          { code: 2239, value: 'Ballia' },
          { code: 2240, value: 'Barauni' },
          { code: 2241, value: 'Begusarai' },
          { code: 2242, value: 'Bhagwanpur' },
          { code: 2243, value: 'Birpur' },
          { code: 2244, value: 'Cheria Bariarpur' },
          { code: 2245, value: 'Chhaurahi' },
          { code: 2246, value: 'Dandari' },
          { code: 2247, value: 'Gadhpura' },
          { code: 2248, value: 'Khodawandpur' },
          { code: 2249, value: 'Mansurchak' },
          { code: 2250, value: 'Matihani' },
          { code: 2251, value: 'Nawkothi' },
          { code: 2252, value: 'Sahebpur Kamal' },
          { code: 2253, value: 'Samho Akha Kurha' },
          { code: 2254, value: 'Teghra' },
        ],
      },
      {
        zCode: 1,
        bpList: [
          { code: 2255, value: 'Bihpur' },
          { code: 2256, value: 'Khalgaon' },
          { code: 2257, value: 'Gopalpur' },
          { code: 2258, value: 'Goradih' },
          { code: 2259, value: 'Ismailpur' },
          { code: 2260, value: 'Jagdishpur' },
          { code: 2261, value: 'Kharik' },
          { code: 2262, value: 'Narayanpur' },
          { code: 2263, value: 'Nathnagar' },
          { code: 2264, value: 'Naugachhia' },
          { code: 2265, value: 'Pirpainti' },
          { code: 2266, value: 'Rangrachowk' },
          { code: 2267, value: 'Sabour' },
          { code: 2268, value: 'Shahkund' },
          { code: 2269, value: 'Sonhaula' },
          { code: 2270, value: 'Sultanganj' },
        ],
      },
      {
        zpCode: 184,
        bpList: [
          { code: 2271, value: 'Agiaon' },
          { code: 2272, value: 'Ara' },
          { code: 2273, value: 'Barhara' },
          { code: 2274, value: 'Behea' },
          { code: 2275, value: 'Charpokhari' },
          { code: 2276, value: 'Garhani' },
          { code: 2277, value: 'Jagdishpur' },
          { code: 2278, value: 'Koilwar' },
          { code: 2279, value: 'Piro' },
          { code: 2280, value: 'Sahar' },
          { code: 2281, value: 'Sandesh' },
          { code: 2282, value: 'Shahpur' },
          { code: 2283, value: 'Tarari' },
          { code: 2284, value: 'Udwantnagar' },
        ],
      },
      {
        zpCode: 185,
        bpList: [
          { code: 2285, value: 'Brahmpur' },
          { code: 2286, value: 'Buxar' },
          { code: 2287, value: 'Chakki' },
          { code: 2288, value: 'Chausa' },
          { code: 2289, value: 'Chougain' },
          { code: 2290, value: 'Dumraon' },
          { code: 2291, value: 'Itarhi' },
          { code: 2292, value: 'Kesath' },
          { code: 2293, value: 'Nawanagar' },
          { code: 2294, value: 'Rajpur' },
          { code: 2295, value: 'Simri' },
        ],
      },
      {
        zpCode: 186,
        bpList: [
          { code: 2296, value: 'Alinagar' },
          { code: 2297, value: 'Bahadurpur' },
          { code: 2298, value: 'Baheri' },
          { code: 2299, value: 'Benipur' },
          { code: 2300, value: 'Biraul' },
          { code: 2301, value: 'Darbhanga' },
          { code: 2302, value: 'Gaurabauram' },
          { code: 2303, value: 'Ghanshyampur' },
          { code: 2304, value: 'Hanuman Nagar' },
          { code: 2305, value: 'Hayaghat' },
          { code: 2306, value: 'Jale' },
          { code: 2307, value: 'Keotirunway' },
          { code: 2308, value: 'Kiratpur' },
          { code: 2309, value: 'Kusheshwar Asthan' },
          { code: 2310, value: 'Kusheswar Asthan East' },
          { code: 2311, value: 'Manigachhi' },
          { code: 2312, value: 'Singhwara' },
          { code: 2313, value: 'Tardih' },
        ],
      },
      {
        zpCode: 187,
        bpList: [
          { code: 2314, value: 'Amas' },
          { code: 2315, value: 'Atri' },
          { code: 2316, value: 'Bankey Bazar' },
          { code: 2317, value: 'Barachatti' },
          { code: 2318, value: 'Belaganj' },
          { code: 2319, value: 'Bodhgaya' },
          { code: 2320, value: 'Dobhi' },
          { code: 2321, value: 'Dumaria' },
          { code: 2322, value: 'Fatehpur' },
          { code: 2323, value: 'Gaya Town' },
          { code: 2324, value: 'Guraru' },
          { code: 2325, value: 'Gurua' },
          { code: 2326, value: 'Imamganj' },
          { code: 2327, value: 'Khizarsarai' },
          { code: 2328, value: 'Konch' },
          { code: 2329, value: 'Manpur' },
          { code: 2330, value: 'Mohanpur' },
          { code: 2331, value: 'Mohra' },
          { code: 2332, value: 'Neemchak Bathani' },
          { code: 2333, value: 'Paraiya' },
          { code: 2334, value: 'Sherghatty' },
          { code: 2335, value: 'Tankuppa' },
          { code: 2336, value: 'Tekari' },
          { code: 2337, value: 'Wazirganj' },
        ],
      },
      {
        zpCode: 189,
        bpList: [
          { code: 2352, value: 'Barhat' },
          { code: 2353, value: 'Chakai' },
          { code: 2354, value: 'Gidhor' },
          { code: 2355, value: 'Islamnagar Aliganj' },
          { code: 2356, value: 'Jamui' },
          { code: 2357, value: 'Jhajha' },
          { code: 2358, value: 'Khaira' },
          { code: 2359, value: 'Laxmipur' },
          { code: 2360, value: 'Sikandra' },
          { code: 2361, value: 'Sono' },
        ],
      },
      {
        zpCode: 458,
        bpList: [
          { code: 5039, value: 'Agali' },
          { code: 5040, value: 'Amadagur' },
          { code: 5041, value: 'Amarapuram' },
          { code: 5042, value: 'Anantapur' },
          { code: 5043, value: 'Atmakur' },
          { code: 5044, value: 'Bathalapalle' },
          { code: 5045, value: 'Beluguppa' },
          { code: 5046, value: 'Bommanahal' },
          { code: 5047, value: 'Brahmasamudram' },
          { code: 5048, value: 'Bukkapatnam' },
          { code: 5049, value: 'Bukkarayasamudram' },
          { code: 5050, value: 'Chennekothapalle' },
          { code: 5051, value: 'Chilamathur' },
          { code: 5052, value: 'D.Hirehal' },
          { code: 5053, value: 'Dharmavaram' },
          { code: 5054, value: 'Gandlapenta' },
          { code: 5055, value: 'Garladinne' },
          { code: 5056, value: 'Gooty' },
          { code: 5057, value: 'Gorantla' },
          { code: 5058, value: 'Gudibanda' },
          { code: 5059, value: 'Gummagatta' },
          { code: 5060, value: 'Guntakal' },
          { code: 5061, value: 'Hindupur' },
          { code: 5062, value: 'Kadiri' },
          { code: 5063, value: 'Kalyandrug' },
          { code: 5064, value: 'Kambadur' },
          { code: 5065, value: 'Kanaganapalle' },
          { code: 5066, value: 'Kanekal' },
          { code: 5067, value: 'Kothacheruvu' },
          { code: 5068, value: 'Kudair' },
          { code: 5069, value: 'Kundurpi' },
          { code: 5070, value: 'Lepakshi' },
          { code: 5071, value: 'Madakasira' },
          { code: 5072, value: 'Mudigubba' },
          { code: 5073, value: 'Nallacheruvu' },
          { code: 5074, value: 'Nallamada' },
          { code: 5075, value: 'Nambulapulikunta' },
          { code: 5076, value: 'Narpala' },
          { code: 5077, value: 'Obuladevarecheruvu' },
          { code: 5078, value: 'Pamidi' },
          { code: 5079, value: 'Parigi' },
          { code: 5080, value: 'Peddapappur' },
          { code: 5081, value: 'Peddavadugur' },
          { code: 5082, value: 'Penukonda' },
          { code: 5083, value: 'Putlur' },
          { code: 5084, value: 'Puttaparthi' },
          { code: 5085, value: 'Ramagiri' },
          { code: 5086, value: 'Raptadu' },
          { code: 5087, value: 'Rayadurg' },
          { code: 5088, value: 'Roddam' },
          { code: 5089, value: 'Rolla' },
          { code: 5090, value: 'Settur' },
          { code: 5091, value: 'Singanamala' },
          { code: 5092, value: 'Somandepalle' },
          { code: 5093, value: 'Tadimarri' },
          { code: 5094, value: 'Tadipatri' },
          { code: 5095, value: 'Talupula' },
          { code: 5096, value: 'Tanakal' },
          { code: 5097, value: 'Uravakonda' },
          { code: 5098, value: 'Vajrakarur' },
          { code: 5099, value: 'Vidapanakal' },
          { code: 5100, value: 'Yadiki' },
          { code: 5101, value: 'Yellanur' },
        ],
      },
      {
        zpCode: 459,
        bpList: [
          { code: 5102, value: 'B.Kothakota' },
          { code: 5103, value: 'Baireddipalle' },
          { code: 5104, value: 'Bangarupalem' },
          { code: 5105, value: 'Buchinadidu Khandriga' },
          { code: 5106, value: 'Chandragiri' },
          { code: 5107, value: 'Chinnagottigallu' },
          { code: 5108, value: 'Chittoor' },
          { code: 5109, value: 'Chowdepalle' },
          { code: 5110, value: 'Gangadhara Nellore' },
          { code: 5111, value: 'Gangavaram' },
          { code: 5112, value: 'Gudipala' },
          { code: 5113, value: 'Gudupalle' },
          { code: 5114, value: 'Gurramkonda' },
          { code: 5115, value: 'Irala' },
          { code: 5116, value: 'K.V.B.Puram' },
          { code: 5117, value: 'Kalakada' },
          { code: 5118, value: 'Kalikiri' },
          { code: 5119, value: 'Kambhamvaripalle' },
          { code: 5120, value: 'Karvetinagar' },
          { code: 5121, value: 'Kuppam' },
          { code: 5122, value: 'Kurabalakota' },
          { code: 5123, value: 'Madanapalle' },
          { code: 5124, value: 'Mulakalacheruvu' },
          { code: 5125, value: 'Nagalapuram' },
          { code: 5126, value: 'Nagari' },
          { code: 5127, value: 'Narayanavanam' },
          { code: 5128, value: 'Nimmanapalle' },
          { code: 5129, value: 'Nindra' },
          { code: 5130, value: 'Pakala' },
          { code: 5131, value: 'Palamaner' },
          { code: 5132, value: 'Palasamudram' },
          { code: 5133, value: 'Peddamandyam' },
          { code: 5134, value: 'Peddapanjani' },
          { code: 5135, value: 'Peddathippasamudram' },
          { code: 5136, value: 'Penumuru' },
          { code: 5137, value: 'Piler' },
          { code: 5138, value: 'Pitchatur' },
          { code: 5139, value: 'Pulicherla Ho Reddivaripalle' },
          { code: 5140, value: 'Punganur' },
          { code: 5141, value: 'Puthalapattu' },
          { code: 5142, value: 'Puttur' },
          { code: 5143, value: 'Ramachandrapuram' },
          { code: 5144, value: 'Ramakuppam' },
          { code: 5145, value: 'Ramasamudram' },
          { code: 5146, value: 'Renigunta' },
          { code: 5147, value: 'Rompicherla' },
          { code: 5148, value: 'Santhipuram Ho Arimuthanapalle' },
          { code: 5149, value: 'Satyavedu' },
          { code: 5150, value: 'Sodam' },
          { code: 5151, value: 'Somala' },
          { code: 5152, value: 'Srikalahasti' },
          { code: 5153, value: 'Srirangarajapuram' },
          { code: 5154, value: 'Thamballapalle' },
          { code: 5155, value: 'Thavanampalle' },
          { code: 5156, value: 'Thottambedu' },
          { code: 5157, value: 'Tirupati (Rural)' },
          { code: 5158, value: 'Vadamalapeta' },
          { code: 5159, value: 'Valmikipuram' },
          { code: 5160, value: 'Varadaiahpalem' },
          { code: 5161, value: 'Vedurukuppam' },
          { code: 5162, value: 'Venkatagirikota' },
          { code: 5163, value: 'Vijayapuram' },
          { code: 5164, value: 'Yadamari' },
          { code: 5165, value: 'Yerpedu' },
          { code: 5166, value: 'Yerravaripalem' },
        ],
      },
      {
        zpCode: 460,
        bpList: [
          { code: 5167, value: 'Atlur' },
          { code: 5168, value: 'B.Kodur' },
          { code: 5169, value: 'Badvel' },
          { code: 5170, value: 'Brahmamgarimatham.' },
          { code: 5171, value: 'Chakrayapet' },
          { code: 5172, value: 'Chapadu' },
          { code: 5173, value: 'Chennur' },
          { code: 5174, value: 'Chinnamandem' },
          { code: 5175, value: 'Chintakomma Dinne' },
          { code: 5176, value: 'Chitvel' },
          { code: 5177, value: 'Duvvur' },
          { code: 5178, value: 'Galiveedu' },
          { code: 5179, value: 'Gopavaram' },
          { code: 5180, value: 'Jammalamadugu' },
          { code: 5181, value: 'Kalasapadu' },
          { code: 5182, value: 'Kamalapuram' },
          { code: 5183, value: 'Khajipet' },
          { code: 5184, value: 'Kodur' },
          { code: 5185, value: 'Kondapuram' },
          { code: 5186, value: 'Lakkireddipalle' },
          { code: 5187, value: 'Lingala' },
          { code: 5188, value: 'Muddanur' },
          { code: 5189, value: 'Mydukur' },
          { code: 5190, value: 'Mylavaram' },
          { code: 5191, value: 'Nandalur' },
          { code: 5192, value: 'Obulavaripalle' },
          { code: 5193, value: 'Peddamudium' },
          { code: 5194, value: 'Penagalur' },
          { code: 5195, value: 'Pendlimarri' },
          { code: 5196, value: 'Porumamilla' },
          { code: 5197, value: 'Proddatur' },
          { code: 5198, value: 'Pulivendla' },
          { code: 5199, value: 'Pullampeta' },
          { code: 5200, value: 'Rajampet' },
          { code: 5201, value: 'Rajupalem' },
          { code: 5202, value: 'Ramapuram' },
          { code: 5203, value: 'Rayachoty' },
          { code: 5204, value: 'Sambepalle' },
          { code: 5205, value: 'Sidhout' },
          { code: 5206, value: 'Simhadripuram' },
          { code: 5207, value: 'Sri Avadutha Kasinayana' },
          { code: 5208, value: 'T.Sundupalle' },
          { code: 5209, value: 'Thondur' },
          { code: 5210, value: 'Vallur' },
          { code: 5211, value: 'Veeraballi' },
          { code: 5212, value: 'Veerapanayani Palle' },
          { code: 5213, value: 'Vempalle' },
          { code: 5214, value: 'Vemula' },
          { code: 5215, value: 'Vontimitta' },
          { code: 5216, value: 'Yerraguntla' },
        ],
      },
      {
        zpCode: 461,
        bpList: [
          { code: 5217, value: 'Addateegala' },
          { code: 5218, value: 'Ainavilli' },
          { code: 5219, value: 'Alamuru' },
          { code: 5220, value: 'Allavaram' },
          { code: 5221, value: 'Amalapuram' },
          { code: 5222, value: 'Ambajipeta' },
          { code: 5223, value: 'Anaparthy' },
          { code: 5224, value: 'Atreyapuram' },
          { code: 5225, value: 'Biccavolu' },
          { code: 5226, value: 'Devipatnam' },
          { code: 5227, value: 'Gandepalle' },
          { code: 5228, value: 'Gangavaram' },
          { code: 5229, value: 'Gokavaram' },
          { code: 5230, value: 'Gollaprolu' },
          { code: 5231, value: 'I. Polavaram' },
          { code: 5232, value: 'Jaggampeta' },
          { code: 5233, value: 'Kadiam' },
          { code: 5234, value: 'Kajuluru' },
          { code: 5235, value: 'Kakinada Rural' },
          { code: 5236, value: 'Kapileswarapuram' },
          { code: 5237, value: 'Karapa' },
          { code: 5238, value: 'Katrenikona' },
          { code: 5239, value: 'Kirlampudi' },
          { code: 5240, value: 'Korukonda' },
          { code: 5241, value: 'Kotananduru' },
          { code: 5242, value: 'U.Kothapalle' },
          { code: 5243, value: 'Kothapeta' },
          { code: 5244, value: 'Malikipuram' },
          { code: 5245, value: 'Mamidikuduru' },
          { code: 5246, value: 'Mandapeta' },
          { code: 5247, value: 'Maredumilli' },
          { code: 5248, value: 'Mummidivaram' },
          { code: 5249, value: 'P.Gannavaram' },
          { code: 5250, value: 'Pamarru' },
          { code: 5251, value: 'Pedapudi' },
          { code: 5252, value: 'Peddapuram' },
          { code: 5253, value: 'Pithapuram' },
          { code: 5254, value: 'Prathipadu' },
          { code: 5255, value: 'Rajahmundry Rural' },
          { code: 5256, value: 'Rajanagaram' },
          { code: 5257, value: 'Rajavommangi' },
          { code: 5258, value: 'Ramachandrapuram' },
          { code: 5259, value: 'Rampachodavaram' },
          { code: 5260, value: 'Rangampeta' },
          { code: 5261, value: 'Ravulapalem' },
          { code: 5262, value: 'Rayavaram' },
          { code: 5263, value: 'Razole' },
          { code: 5264, value: 'Sakhinetipalle' },
          { code: 5265, value: 'Samalkota' },
          { code: 5266, value: 'Sankhavaram' },
          { code: 5267, value: 'Seethanagaram' },
          { code: 5268, value: 'Thallarevu' },
          { code: 5269, value: 'Thondangi' },
          { code: 5270, value: 'Tuni' },
          { code: 5271, value: 'Uppalaguptam' },
          { code: 5272, value: 'Y. Ramavaram' },
          { code: 5273, value: 'Yeleswaram' },
        ],
      },
      {
        zpCode: 462,
        bpList: [
          { code: 5274, value: 'Amaravathi' },
          { code: 5275, value: 'Amruthalur' },
          { code: 5276, value: 'Atchempet' },
          { code: 5277, value: 'Bapatla' },
          { code: 5278, value: 'Bellamkonda' },
          { code: 5279, value: 'Bhattiprolu' },
          { code: 5280, value: 'Bollapalle' },
          { code: 5281, value: 'Chebrole' },
          { code: 5282, value: 'Cherukupalle' },
          { code: 5283, value: 'Chilakaluripet' },
          { code: 5284, value: 'Dachepalle' },
          { code: 5285, value: 'Duggirala' },
          { code: 5286, value: 'Durgi' },
          { code: 5287, value: 'Edlapadu' },
          { code: 5288, value: 'Guntur' },
          { code: 5289, value: 'Gurazala' },
          { code: 5290, value: 'Ipur' },
          { code: 5291, value: 'Kakumanu' },
          { code: 5292, value: 'Karempudi' },
          { code: 5293, value: 'Karlapalem' },
          { code: 5294, value: 'Kollipara' },
          { code: 5295, value: 'Kollur' },
          { code: 5296, value: 'Krosuru' },
          { code: 5297, value: 'Machavaram' },
          { code: 5298, value: 'Macherla' },
          { code: 5299, value: 'Mangalagiri' },
          { code: 5300, value: 'Medikonduru' },
          { code: 5301, value: 'Muppalla' },
          { code: 5302, value: 'Nadendla' },
          { code: 5303, value: 'Nagaram' },
          { code: 5304, value: 'Narasaraopeta' },
          { code: 5305, value: 'Nekarikallu' },
          { code: 5306, value: 'Nizampatnam' },
          { code: 5307, value: 'Nuzendla' },
          { code: 5308, value: 'Pedakakani' },
          { code: 5309, value: 'Pedakurapadu' },
          { code: 5310, value: 'Pedanandipadu' },
          { code: 5311, value: 'Phirangipuram' },
          { code: 5312, value: 'Piduguralla' },
          { code: 5313, value: 'Pittalavanipalem' },
          { code: 5314, value: 'Ponnur' },
          { code: 5315, value: 'Prathipadu' },
          { code: 5316, value: 'Rajupalem' },
          { code: 5317, value: 'Rentachintala' },
          { code: 5318, value: 'Repalle' },
          { code: 5319, value: 'Rompicherla' },
          { code: 5320, value: 'Sattenapalle' },
          { code: 5321, value: 'Savalyapuram' },
          { code: 5322, value: 'Tadepalle' },
          { code: 5323, value: 'Tadikonda' },
          { code: 5324, value: 'Tenali' },
          { code: 5325, value: 'Thullur' },
          { code: 5326, value: 'Tsundur' },
          { code: 5327, value: 'Vatticherukuru' },
          { code: 5328, value: 'Veldurthy' },
          { code: 5329, value: 'Vemuru' },
          { code: 5330, value: 'Vinukonda' },
        ],
      },
      {
        zpCode: 465,
        bpList: [
          { code: 5434, value: 'A.Konduru' },
          { code: 5435, value: 'Agiripalli' },
          { code: 5436, value: 'Avanigadda' },
          { code: 5437, value: 'Bantumilli' },
          { code: 5438, value: 'Bapulapadu' },
          { code: 5439, value: 'Challapalli' },
          { code: 5440, value: 'Chandarlapadu' },
          { code: 5441, value: 'Chatrai' },
          { code: 5442, value: 'G.Konduru' },
          { code: 5443, value: 'Gampalagudem' },
          { code: 5444, value: 'Gannavaram' },
          { code: 5445, value: 'Ghantasala' },
          { code: 5446, value: 'Gudivada' },
          { code: 5447, value: 'Gudlavalleru' },
          { code: 5448, value: 'Guduru' },
          { code: 5449, value: 'Ibrahimpatnam' },
          { code: 5450, value: 'Jaggayyapeta' },
          { code: 5451, value: 'Kaikalur' },
          { code: 5452, value: 'Kalidindi' },
          { code: 5453, value: 'Kanchikacherla' },
          { code: 5454, value: 'Kankipadu' },
          { code: 5455, value: 'Koduru' },
          { code: 5456, value: 'Kruttivennu' },
          { code: 5457, value: 'Machilipatnam' },
          { code: 5458, value: 'Mandavalli' },
          { code: 5459, value: 'Mopidevi' },
          { code: 5460, value: 'Movva' },
          { code: 5461, value: 'Mudinepalle' },
          { code: 5462, value: 'Musunuru' },
          { code: 5463, value: 'Mylavaram' },
          { code: 5464, value: 'Nagayalanka' },
          { code: 5465, value: 'Nandigama' },
          { code: 5466, value: 'Nandivada' },
          { code: 5467, value: 'Nuzvid' },
          { code: 5468, value: 'Pamarru' },
          { code: 5469, value: 'Pamidimukkala' },
          { code: 5470, value: 'Pedana' },
          { code: 5471, value: 'Pedaparupudi' },
          { code: 5472, value: 'Penamaluru' },
          { code: 5473, value: 'Penuganchiprolu' },
          { code: 5474, value: 'Reddigudem' },
          { code: 5475, value: 'Thotlavalluru' },
          { code: 5476, value: 'Tiruvuru' },
          { code: 5477, value: 'Unguturu' },
          { code: 5478, value: 'Vatsavai' },
          { code: 5479, value: 'Veerullapadu' },
          { code: 5480, value: 'Vijayawada Rural' },
          { code: 5481, value: 'Vissannapet' },
          { code: 5482, value: 'Vuyyuru' },
        ],
      },
      {
        zpCode: 466,
        bpList: [
          { code: 5483, value: 'Adoni' },
          { code: 5484, value: 'Allagadda' },
          { code: 5485, value: 'Alur' },
          { code: 5486, value: 'Aspari' },
          { code: 5487, value: 'Atmakur' },
          { code: 5488, value: 'Banaganapalle' },
          { code: 5489, value: 'Bandi Atmakur' },
          { code: 5490, value: 'Bethamcherla' },
          { code: 5491, value: 'C.Belagal' },
          { code: 5492, value: 'Chagalamarri' },
          { code: 5493, value: 'Chippagiri' },
          { code: 5494, value: 'Devanakonda' },
          { code: 5495, value: 'Dhone Alias Dronachalam' },
          { code: 5496, value: 'Dornipadu' },
          { code: 5497, value: 'Gadivemula' },
          { code: 5498, value: 'Gonegandla' },
          { code: 5499, value: 'Gospadu' },
          { code: 5500, value: 'Gudur' },
          { code: 5501, value: 'Halaharvi' },
          { code: 5502, value: 'Holagunda' },
          { code: 5503, value: 'Jupadu Bungalow' },
          { code: 5504, value: 'Kallur' },
          { code: 5505, value: 'Kodumur' },
          { code: 5506, value: 'Koilakuntla' },
          { code: 5507, value: 'Kolimigundla' },
          { code: 5508, value: 'Kosigi' },
          { code: 5509, value: 'Kothapalle' },
          { code: 5510, value: 'Kowthalam' },
          { code: 5511, value: 'Krishnagiri' },
          { code: 5512, value: 'Kurnool' },
          { code: 5513, value: 'Maddikera (East)' },
          { code: 5514, value: 'Mahanandi' },
          { code: 5515, value: 'Mantralayam' },
          { code: 5516, value: 'Midthur' },
          { code: 5517, value: 'Nandavaram' },
          { code: 5518, value: 'Nandikotkur' },
          { code: 5519, value: 'Nandyal' },
          { code: 5520, value: 'Orvakal' },
          { code: 5521, value: 'Owk' },
          { code: 5522, value: 'Pagidyala' },
          { code: 5523, value: 'Pamulapadu' },
          { code: 5524, value: 'Panyam' },
          { code: 5525, value: 'Pattikonda' },
          { code: 5526, value: 'Peapully' },
          { code: 5527, value: 'Peddakadabur' },
          { code: 5528, value: 'Rudravaram' },
          { code: 5529, value: 'Sanjamala' },
          { code: 5530, value: 'Sirivel' },
          { code: 5532, value: 'Tuggali' },
          { code: 5533, value: 'Uyyalawada' },
          { code: 5534, value: 'Veldurthi' },
          { code: 5535, value: 'Velugodu' },
          { code: 5536, value: 'Yemmiganur' },
        ],
      },
      {
        zpCode: 470,
        bpList: [
          { code: 5706, value: 'Allur' },
          { code: 5707, value: 'Ananthasagaram' },
          { code: 5708, value: 'Anumasamudrampeta' },
          { code: 5709, value: 'Atmakur' },
          { code: 5710, value: 'Balayapalle' },
          { code: 5711, value: 'Bogole' },
          { code: 5712, value: 'Butchireddipalem' },
          { code: 5713, value: 'Chejerla' },
          { code: 5714, value: 'Chillakur' },
          { code: 5715, value: 'Chittamur' },
          { code: 5716, value: 'Dagadarthi' },
          { code: 5717, value: 'Dakkili' },
          { code: 5718, value: 'Doravarisatram' },
          { code: 5719, value: 'Duttalur' },
          { code: 5720, value: 'Gudur' },
          { code: 5721, value: 'Indukurpet' },
          { code: 5722, value: 'Jaladanki' },
          { code: 5723, value: 'Kaligiri' },
          { code: 5724, value: 'Kaluvoya' },
          { code: 5725, value: 'Kavali' },
          { code: 5726, value: 'Kodavalur' },
          { code: 5727, value: 'Kondapuram' },
          { code: 5728, value: 'Kota' },
          { code: 5729, value: 'Kovur' },
          { code: 5730, value: 'Manubolu' },
          { code: 5731, value: 'Marripadu' },
          { code: 5732, value: 'Muthukur' },
          { code: 5733, value: 'Naidupeta' },
          { code: 5734, value: 'Nellore Rural' },
          { code: 5735, value: 'Ozili' },
          { code: 5736, value: 'Pellakur' },
          { code: 5737, value: 'Podalakur' },
          { code: 5738, value: 'Rapur' },
          { code: 5739, value: 'Sangam' },
          { code: 5740, value: 'Seetharamapuram' },
          { code: 5741, value: 'Sullurpeta' },
          { code: 5742, value: 'Sydapuram' },
          { code: 5743, value: 'Tada' },
          { code: 5744, value: 'Thotapalligudur' },
          { code: 5745, value: 'Udayagiri' },
          { code: 5746, value: 'Vakadu' },
          { code: 5747, value: 'Varikuntapadu' },
          { code: 5748, value: 'Venkatachalam' },
          { code: 5749, value: 'Venkatagiri' },
          { code: 5750, value: 'Vidavalur' },
          { code: 5751, value: 'Vinjamur' },
        ],
      },
      {
        zpCode: 472,
        bpList: [
          { code: 5788, value: 'Addanki' },
          { code: 5789, value: 'Ardhaveedu' },
          { code: 5790, value: 'Ballikurava' },
          { code: 5791, value: 'Bestavaripeta' },
          { code: 5792, value: 'Chandra Sekhara Puram' },
          { code: 5793, value: 'Chimakurthi' },
          { code: 5794, value: 'Chinaganjam' },
          { code: 5795, value: 'Chirala' },
          { code: 5796, value: 'Cumbum' },
          { code: 5797, value: 'Darsi' },
          { code: 5798, value: 'Donakonda' },
          { code: 5799, value: 'Dornala' },
          { code: 5800, value: 'Giddaluru' },
          { code: 5801, value: 'Gudluru' },
          { code: 5802, value: 'Hanumanthuni Padu' },
          { code: 5803, value: 'Inkollu' },
          { code: 5804, value: 'Janakavaram Ponguluru' },
          { code: 5805, value: 'Kandukur' },
          { code: 5806, value: 'Kanigiri' },
          { code: 5807, value: 'Karamchedu' },
          { code: 5808, value: 'Komarolu' },
          { code: 5809, value: 'Konakanamittla' },
          { code: 5810, value: 'Kondapi' },
          { code: 5811, value: 'Korisapadu' },
          { code: 5812, value: 'Kotha Patnam' },
          { code: 5813, value: 'Kurichedu' },
          { code: 5814, value: 'Lingasamudram' },
          { code: 5815, value: 'Maddipadu' },
          { code: 5816, value: 'Markapur' },
          { code: 5817, value: 'Marripudi' },
          { code: 5818, value: 'Martur' },
          { code: 5819, value: 'Mundlamuru' },
          { code: 5820, value: 'Naguluppala Padu' },
          { code: 5821, value: 'Ongole' },
          { code: 5822, value: 'Pamur' },
          { code: 5823, value: 'Parchur' },
          { code: 5824, value: 'Peda Araveedu' },
          { code: 5825, value: 'Pedacherlo Palle' },
          { code: 5826, value: 'Podili' },
          { code: 5827, value: 'Ponnaluru' },
          { code: 5828, value: 'Pullalacheruvu' },
          { code: 5829, value: 'Racherla' },
          { code: 5830, value: 'Santhamaguluru' },
          { code: 5831, value: 'Santhanuthala Padu' },
          { code: 5832, value: 'Singarayakonda' },
          { code: 5833, value: 'Tangutur' },
          { code: 5834, value: 'Tarlupadu' },
          { code: 5835, value: 'Tallur' },
          { code: 5836, value: 'Tripuranthakam' },
          { code: 5837, value: 'Ulavapadu' },
          { code: 5838, value: 'Veligandla' },
          { code: 5839, value: 'Vetapalem' },
          { code: 5840, value: 'Voletivari Palem' },
          { code: 5841, value: 'Yddana Pudi' },
          { code: 5842, value: 'Yerragondapalem' },
          { code: 5843, value: 'Zarugumilli' },
        ],
      },
    ];
  }
}
